POST http://localhost:8080/api/order
Content-Type: application/json

{
  "products": []
}

###
POST http://localhost:8080/api/product
Content-Type: application/json

{
  "name": "Vysocina",
  "price": 32,
  "quantity": 5,
  "unit": "kg"
}

###
POST http://localhost:8080/api/order
Content-Type: application/json

{
  "products": [
    {
      "productId": "4e2c0540-1544-45ba-966d-7b7f05816000",
      "quantity": 1,
      "unit": "kg"
    }
  ]
}


###
PATCH http://localhost:8080/api/order/586dd468-4ce9-485e-bd0f-9b6fcfd673d2/pay

###
PATCH http://localhost:8080/api/order/586dd468-4ce9-485e-bd0f-9b6fcfd673d2/cancel